### ISSUE TITLE
How do I build the .modl file?

### ISSUE THREAD

**Issue by ia-eknorr** [design-group/ignition-tag-cicd-module#4]
I'm trying to work on getting an instance of this set up on my machine. I was able to kind of build a .modl with gradle 8.1.1, but not gradle 6.9.4. 

Gradle 8.1.1 initially failed to build because compile() was deprecated in gradle 7.
Gradle 6.9.4 failed because `keystore` and `certFile` do no exist. I didn't explore further.

Now, although 8.1.1 failed initially, I was able to get a partial build that installs in Ignition by replacing [compile(project(":common")](https://github.com/design-group/ignition-tag-cicd-module/blob/c44d04ee3e7be9ef9b0cb1b7058411288ed013d1/gateway/build.gradle#L10)
 with `implementation project(':common')`. But it still said it failed. 

That being said, I tried to install the module that I got from gradle 8.1.1 (that failed but still gave me a module), and it seems to install properly. I tried running `curl http://localhost:9300/data/tag-cicd/tags/export\?recursive\=true -o tag_configuration.json`, but from the documentation on this repo, I'm unsure what to expect. But I don't see a `tag_configuration.json` file anywhere, so I suspect it didn't work..?

**Comment by keith-gamble** [comment]
Added details on how to build the module into the readme

I am currently leveraging
```
------------------------------------------------------------
Gradle 7.2
------------------------------------------------------------

Build time:   2021-08-17 09:59:03 UTC
Revision:     a773786b58bb28710e3dc96c4d1a7063628952ad

Kotlin:       1.5.21
Groovy:       3.0.8
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.16.1 (Oracle Corporation 11.0.16.1+1-LTS-1)
OS:           Mac OS X 14.4 aarch64
```
