### ISSUE TITLE
Tag files not deleted when using `individualFilesPerObject`

### ISSUE THREAD

**Issue by ia-eknorr** [design-group/ignition-tag-cicd-module#6]
# Description

We are using `individualFilesPerObject`. When exporting tags after deleting a tag in the designer, the corresponding JSON file in VSCode is not removed. This makes intuitive sense since the export is exporting all what IS in Ignition, and not what is NOT in Ignition.

## Expected outcome

Deleted tag def is removed in the `filePath` tree, and shows as a deleted file in source control

## Actual outcome

Deleted tag def remains in structure in the `filePath` tree, and is not modified or deleted in source control

## Proposed Solution

Remove all tags in the `filePath` before exporting when using `individualFilesPerObject`. (this is likely not an issue if not using `individualFilesPerObject` since all the tags are in a couple json files instead of many)

## Procedure to recreate
1. Setup ignition
  * Ignition instance
  * At least 2 tag instances
2. Export tags using `individualFilesPerObject`
3. Delete a tag from Ignition designer
4. Export tags again
5. Observe that the deleted tag remains in the `filePath` tree, and has not been deleted or modified.

**Comment by keith-gamble** [comment]
Fixed with v0.0.4

Added a new `deleteExisting` argument to the export endpoint. This will tell the module to delete any of the local files that are not a part of our export.

Also added the `-d` flag to the `./docker/scripts/tag-export.sh` example
