### ISSUE TITLE
Many files slightly modified on export

### ISSUE THREAD

**Issue by ia-eknorr** [design-group/ignition-tag-cicd-module#7]
# Description

When exporting tags (in our case, specifically using `individualFilesPerObject`), basically all of the individual tag objects have slight modifications, ranging from a couple lines getting swapped, to large hunks changing locations within the tag json. This happens every time whether there has been a modification or not. If these modifications are added and committed, they won't show up with another export, but if the ignition service is restarted, and another export is made, these bogus modifications will show up. 

This is a huge hinderance to our workflow as we have to remember which changes we actually made, or diff the file to see that changes we made didn't impact this tag. We run a major risk of losing tag changes since basically all of the tags change.

## Current behavior

On export, slight modifications to nearly every tag definition appear.

## Expected behavior

When taking an export, only modified tags jsons should show as modified

## Potential fix

Is it possible to use an ordered type and sort the actual `tags` list in each json to be alphanumerically sorted?

## To recreate

It's most clear to see this if we add a tag, although it's not strictly necessary. This will take you through the procedure to recreate.

1. Set up Ignition
  * Ignition instance
  * Several tags
  * Export with `individualFilesPerObject` enabled
  * Spin up the stack
2. In the designer, add a tag
3. Take a tag export
4. Observe your new tag, with a bunch of modified tags that you didn't modify
<img width="351" alt="image" src="https://github.com/design-group/ignition-tag-cicd-module/assets/50336131/510daf7d-7eaa-4c61-ad38-6902a737a82f">

The diff clearly shows that two instances that switched places in the tag list, and all the chile tags got moved with it, but no actual changes were made here. ([machine2_diff.txt](https://github.com/design-group/ignition-tag-cicd-module/files/15002068/machine2_diff.txt))

<img width="1311" alt="image" src="https://github.com/design-group/ignition-tag-cicd-module/assets/50336131/2d18185c-2cb3-43c3-810b-fe022d8249ad">

**Comment by ia-eknorr** [comment]
I tested this without `individualFilesPerObject` and it has the same result, maybe even worse. I followed the same procedure, but kept everything in one file. It's like everything changed places. ([tags_json_diff.txt](https://github.com/design-group/ignition-tag-cicd-module/files/15002549/tags_json_diff.txt))

**Comment by keith-gamble** [comment]
Fixed with v0.0.4

The native `JsonUtilities.createDeterministicCopy` was not working, so instead I just added a custom json sorter.
